@startuml
'https://plantuml.com/class-diagram

interface Hero
abstract class GeneralHero
class DecoratorHero
class Wizard
class Archer
class Warrior
class LightTeam
class DarkTeam
class Battle
class Elf
class Human
class Orc
class Undead

GeneralHero --|> Hero
DecoratorHero --|> Hero
DecoratorHero *-- Hero
Wizard --|> DecoratorHero
Archer --|> DecoratorHero
Warrior --|> DecoratorHero
Elf o-- Wizard
Elf o-- Archer
Elf o-- Warrior
Human o-- Wizard
Human o-- Archer
Human o-- Warrior
Orc o-- Wizard
Orc o-- Archer
Orc o-- Warrior
Undead o-- Wizard
Undead o-- Archer
Undead o-- Warrior
LightTeam o-- Elf
LightTeam o-- Human
DarkTeam o-- Orc
DarkTeam o-- Undead
Battle *-- DarkTeam
Battle *-- LightTeam

@enduml